### ISSUE TITLE
Check, disable/remove the use of GoogleAnalytics from OkHttp

### ISSUE THREAD

**Issue by wischweh** [Qabel/qabel-android#238]
From the test logs (see below) it seems like OkHttp is using GoogleAnalytics. This is not acceptable with a product focusing on privacy. Please check, disable or better remove GA from OkHttp.

**Comment by wischweh** [comment]
Here is the excerpt from the test log:
02-17 11:37:17.625 5881-5934/de.qabel.qabelbox W/InfraTrack: Analytics post: AndroidJUnitRunner failed. 
                                                             java.net.ConnectException: failed to connect to www.google-analytics.com/127.0.0.1 (port 80) after 30000ms: isConnected failed: ECONNREFUSED (Connection refused)
                                                                 at libcore.io.IoBridge.isConnected(IoBridge.java:241)
                                                                 at libcore.io.IoBridge.connectErrno(IoBridge.java:174)
                                                                 at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                 at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                 at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
                                                                 at java.net.Socket.connect(Socket.java:882)
                                                                 at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139)
                                                                 at com.android.okhttp.Connection.connect(Connection.java:152)
                                                                 at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:279)
                                                                 at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:213)
                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:208)
                                                                 at android.support.test.internal.runner.tracker.AnalyticsBasedUsageTracker.sendUsages(AnalyticsBasedUsageTracker.java:258)
                                                                 at android.support.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:256)
                                                                 at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:249)
                                                                 at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)
                                                              Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
                                                                 at libcore.io.IoBridge.isConnected(IoBridge.java:226)
                                                                 at libcore.io.IoBridge.connectErrno(IoBridge.java:174) 
                                                                 at libcore.io.IoBridge.connect(IoBridge.java:122) 
                                                                 at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
                                                                 at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456) 
                                                                 at java.net.Socket.connect(Socket.java:882) 
                                                                 at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139) 
                                                                 at com.android.okhttp.Connection.connect(Connection.java:152) 
                                                                 at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:279) 
                                                                 at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:213) 
                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373) 
                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106) 
                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:208) 
                                                                 at android.support.test.internal.runner.tracker.AnalyticsBasedUsageTracker.sendUsages(AnalyticsBasedUsageTracker.java:258) 
                                                                 at android.support.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:256) 
                                                                 at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:249) 
                                                                 at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)

**Comment by audax** [comment]
That is just the testrunner that is sending stuff to google. This is not happening on normal usage afaik.
