### ISSUE TITLE
[blockserver] crash creating 2nd Identity

### ISSUE THREAD

**Issue by wischweh** [Qabel/qabel-android#258]
Affects: current versions of the blockserver branch
This bug can be reproduced in the app as well as by CreateIdentityTest.addIdentity1Test().

Steps; fresh install of app
1. Create Account
2. Create identity foo following the form
3. Navigate back to Create identity (using the navigation drawer)
4. click "create new identity"
5. press back button without entering something
6. Create identity foo1 following the form
Result: App crashes with the following exception

02-22 11:23:52.785 27699-27699/de.qabel.qabelbox E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: de.qabel.qabelbox, PID: 27699
                                                                   java.lang.RuntimeException: Unable to resume activity {de.qabel.qabelbox/de.qabel.qabelbox.activities.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=16, result=-1, data=Intent { (has extras) }} to activity {de.qabel.qabelbox/de.qabel.qabelbox.activities.MainActivity}: java.lang.NullPointerException
                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2774)
                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2803)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238)
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                    Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=16, result=-1, data=Intent { (has extras) }} to activity {de.qabel.qabelbox/de.qabel.qabelbox.activities.MainActivity}: java.lang.NullPointerException
                                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:3351)
                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2761)
                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2803) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238) 
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                                    Caused by: java.lang.NullPointerException
                                                                       at de.qabel.qabelbox.activities.MainActivity.addIdentity(MainActivity.java:716)
                                                                       at de.qabel.qabelbox.activities.MainActivity.onActivityResult(MainActivity.java:137)
                                                                       at android.app.Activity.dispatchActivityResult(Activity.java:5423)
                                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:3347)
                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2761) 
                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2803) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238) 
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by wischweh** [comment]
will be fixed in PR
