### ISSUE TITLE
Remove LocalQabelService

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#548]
We now have dagger to get our dependencies and the LQS likes to crash.

**Comment by audax** [comment]
Example crash:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String de.qabel.core.config.Identity.getKeyIdentifier()' on a null object reference
at de.qabel.desktop.repository.sqlite.SqliteContactRepository.findByKeyId(SqliteContactRepository.java:184)
at de.qabel.qabelbox.services.LocalQabelService.addContact(LocalQabelService.java:175)
at de.qabel.qabelbox.services.LocalQabelService.addContact(LocalQabelService.java:170)
at de.qabel.qabelbox.fragments.ContactBaseFragment.addContactSilent(ContactBaseFragment.java:53)
at de.qabel.qabelbox.fragments.ContactBaseFragment.importContactFromUri(ContactBaseFragment.java:79)
at de.qabel.qabelbox.activities.MainActivity.handleActionViewResolver(MainActivity.java:535)
at de.qabel.qabelbox.activities.MainActivity.handleIntent(MainActivity.java:464)
at de.qabel.qabelbox.activities.MainActivity.onLocalServiceConnected(MainActivity.java:438)
at de.qabel.qabelbox.activities.MainActivity.access$200(MainActivity.java:103)
```

**Comment by JoGir** [comment]
Is removed in #591
