### ISSUE TITLE
Start search -> bring app to background -> app crashs

### ISSUE THREAD

**Issue by hash13** [Qabel/qabel-android#586]
Start a search in filesbrowser
Until search is running, press home to bring app to background
App crashs

See stacktrace

FATAL EXCEPTION: main
                                                   Process: de.qabel.qabel, PID: 21755
                                                   **java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState**
                                                       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1328)
                                                       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1346)
                                                       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:729)
                                                       at android.app.BackStackRecord.commit(BackStackRecord.java:705)
                                                       at de.qabel.qabelbox.fragments.FilesFragment$4.onPostExecute(FilesFragment.java:394)
                                                       at de.qabel.qabelbox.fragments.FilesFragment$4.onPostExecute(FilesFragment.java:360)
                                                       at android.os.AsyncTask.finish(AsyncTask.java:636)
                                                       at android.os.AsyncTask.access$500(AsyncTask.java:177)
                                                       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5499)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

**Comment by jmt85** [comment]
duplicated #584
