### ISSUE TITLE
Instable android tests

### ISSUE THREAD

**Issue by JoGir** [Qabel/qabel-android#607]
1633-1633/de.qabel.qabel.debug D/LifecycleMonitor: Lifecycle status change: de.qabel.qabelbox.activities.MainActivity@aac30d3 in: RESUMED
1633-1721/de.qabel.qabel.debug E/SystemAnimations: can't deactivate animations
1633-1633/de.qabel.qabel.debug E/IdlingResourceRegistry: Attempted to register resource with same names: de.qabel.qabelbox.ui.idling.InjectedIdlingResource. R1: de.qabel.qabelbox.ui.idling.InjectedIdlingResource@f46c6a6 R2: de.qabel.qabelbox.ui.idling.InjectedIdlingResource@c0d58e7.
                                                         Duplicate resource registration will be ignored.
1633-1721/de.qabel.qabel.debug I/de.qabel.qabelbox.ui.idling.InjectedIdlingResource: Setting resource to busy
1633-1633/de.qabel.qabel.debug I/de.qabel.qabelbox.ui.idling.InjectedIdlingResource: Setting resource to idle

**Comment by JoGir** [comment]
1633-1633/de.qabel.qabel.debug E/ActivityThread: Activity de.qabel.qabelbox.activities.MainActivity has leaked IntentReceiver de.qabel.qabelbox.communication.connection.ConnectivityManager$1@6296039 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                 android.app.IntentReceiverLeaked: Activity de.qabel.qabelbox.activities.MainActivity has leaked IntentReceiver de.qabel.qabelbox.communication.connection.ConnectivityManager$1@6296039 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                     at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:919)
                                                     at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:720)
                                                     at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1182)
                                                     at android.app.ContextImpl.registerReceiver(ContextImpl.java:1162)
                                                     at android.app.ContextImpl.registerReceiver(ContextImpl.java:1156)
                                                     at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:560)
                                                     at de.qabel.qabelbox.communication.connection.ConnectivityManager.<init>(ConnectivityManager.java:32)
                                                     at de.qabel.qabelbox.dagger.modules.ActivityModule.provideConnectivityManager(ActivityModule.java:23)
                                                     at de.qabel.qabelbox.dagger.modules.ActivityModule_ProvideConnectivityManagerFactory.get(ActivityModule_ProvideConnectivityManagerFactory.java:24)
                                                     at de.qabel.qabelbox.dagger.modules.ActivityModule_ProvideConnectivityManagerFactory.get(ActivityModule_ProvideConnectivityManagerFactory.java:8)
                                                     at de.qabel.qabelbox.activities.MainActivity_MembersInjector.injectMembers(MainActivity_MembersInjector.java:80)
                                                     at de.qabel.qabelbox.activities.MainActivity_MembersInjector.injectMembers(MainActivity_MembersInjector.java:14)
                                                     at de.qabel.qabelbox.dagger.components.DaggerMockApplicationComponent$ActivityComponentImpl$MainActivityComponentImpl.inject(DaggerMockApplicationComponent.java:527)
                                                     at de.qabel.qabelbox.activities.MainActivity.onCreate(MainActivity.java:183)
                                                     at android.app.Activity.performCreate(Activity.java:6251)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                     at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:532)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by JoGir** [comment]
1633-1633/de.qabel.qabel.debug E/MonitoringInstrumentation: Exception encountered by: Thread[main,5,main]. Dumping thread state to outputs and pining for the fjords.
                                                            junit.framework.AssertionFailedError: Wanted to match 1 intents. Actually matched 0 intents.
                                                            
                                                            IntentMatcher: has component: has component with: class name: a string ending with "WelcomeScreenActivity" package name: an instance of java.lang.String short class name: an instance of java.lang.String
                                                            
                                                            Matched intents:[]
                                                            
                                                            Recorded intents:
                                                            -Intent { flg=0x10000000 cmp=de.qabel.qabel.debug/de.qabel.qabelbox.activities.SplashActivity (has extras) } handling packages:[[de.qabel.qabel.debug]], extras:[Bundle[{SKIP_SPLASH=true}]])
                                                                at junit.framework.Assert.fail(Assert.java:50)
                                                                at android.support.test.espresso.intent.VerificationModes$Times.verify(VerificationModes.java:87)
                                                                at android.support.test.espresso.intent.Intents.internalIntended(Intents.java:282)
                                                                at android.support.test.espresso.intent.Intents$3.run(Intents.java:199)
                                                                at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:1904)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:148)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
1633-1633/de.qabel.qabel.debug E/THREAD_STATE:   Thread[FinalizerDaemon,5,system]
                                                   java.lang.Object.wait(Native Method)
                                                   java.lang.Object.wait(Object.java:423)
                                                   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
                                                   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
                                                   java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
                                                   java.lang.Thread.run(Thread.java:818)
                                               
                                                 Thread[main,5,main]
                                                   dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                   java.lang.Thread.getStackTrace(Thread.java:580)
                                                   java.lang.Thread.getAllStackTraces(Thread.java:522)
                                                   android.support.test.runner.MonitoringInstrumentation.getThreadState(MonitoringInstrumentation.java:501)
                                                   android.support.test.runner.MonitoringInstrumentation.dumpThreadStateToOutputs(MonitoringInstrumentation.java:496)
                                                   android.support.test.runner.MonitoringInstrumentation.onException(MonitoringInstrumentation.java:490)
                                                   android.support.test.runner.AndroidJUnitRunner.onException(AndroidJUnitRunner.java:333)
                                                   android.support.test.runner.MonitoringInstrumentation$3.uncaughtException(MonitoringInstrumentation.java:207)
                                               
                                                 Thread[Okio Watchdog,5,main]
                                                   java.lang.Object.wait(Native Method)
                                                   okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:311)
                                                   okio.AsyncTimeout.access$000(AsyncTimeout.java:40)
                                                   okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:286)
                                               
                                                 Thread[Chrome_InProcRendererThread,5,main]
                                               
                                                 Thread[AsyncTask #4,5,main]
                                                   java.lang.Object.wait(Native Method)
                                                   java.lang.Thread.parkFor$(Thread.java:1220)
                                                   sun.misc.Unsafe.park(Unsafe.java:299)
                                                   java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
                                                   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
                                                   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
                                                   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
                                                   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
                                                   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                   java.lang.Thread.run(Thread.java:818)
                                               
                                                 Thread[OkHttp ConnectionPool,5,main]
                                                   java.lang.Object.wait(Native Method)
                                                   okhttp3.ConnectionPool$1.run(ConnectionPool.java:65)
                                                   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                   java.lang.Thread.run(Thread.java:818)
                                               
                                                 Thread[Thread-28908,5,main]
                                               
                                                 Thread[Espresso Key Event #0,5,main]
                                                   java.lang.Object.wait(Native Method)
                                                   java.lang.Thread.parkFor$(Thread.java:1220)
                                                   sun.misc.Unsafe.park(Unsafe.java:299)
                                                   java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
                                                   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
                                                   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
                                                   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
                                                   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
                                                   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                   java.lang.Thread.run(Thread.java:818)
                                               
                                                 Thread[OkHttp ConnectionPool,5,main]
                                                   java.lang.Object.wait(Native Method)
                                                   okhttp3.ConnectionPool$1.run(ConnectionPool.java:65)
                                                   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                   java.lang.Thread.run(Thread.java:818)
                                               
                                                 Thread[Binder_1,5,main]
                                               
                                                 Thread[JDWP,5,system]
                                               
                                                 Thread[Binder_3,5,main]
                                               
                                                 Thread[Chrome_FileThread,5,main]
                                               
                                                 Thread[ReferenceQueueDaemon,5,system]
                                                   java.lang.Object.wait(Native Method)
                                                   java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:147)
                                                   java.lang.Thread.run(Thread.java:818)
                                               
                                                 Thread[RenderThread,5,main]
                                               
                                                 Thread[Chrome_FileUserBlockingThread,5,main]
                                               
                                                 Thread[Thread-28925,5,main]
                                                   java.lang.Object.wait(Native Method)
                                                   java.lang.Thread.parkFor$(Thread.java:1220)
                                                   su
