### ISSUE TITLE
Error in FileBrowser after importing identity

### ISSUE THREAD

**Issue by JoGir** [Qabel/qabel-android#646]
```
09-04 05:47:58.631 22016-27164/de.qabel.qabel.debug E/SQLiteLog: (1) table meta already exists
09-04 05:47:58.674 22016-22016/de.qabel.qabel.debug E/FileBrowserFragment: Error
de.qabel.core.repository.sqlite.migration.MigrationFailedException: android.database.sqlite.SQLiteException: table meta already exists (code 1): , 
while compiling: CREATE TABLE meta (
                name VARCHAR(24) PRIMARY KEY,
                value TEXT )
    at de.qabel.core.repository.sqlite.AbstractClientDatabase.migrate(AbstractClientDatabase.kt:51)
    at de.qabel.core.repository.sqlite.AbstractClientDatabase.migrate(AbstractClientDatabase.kt:38)
    at de.qabel.core.repository.sqlite.AbstractClientDatabase.migrateTo(AbstractClientDatabase.kt:24)
    at de.qabel.core.repository.sqlite.AbstractClientDatabase.migrate(AbstractClientDatabase.kt:71)
    at de.qabel.box.storage.jdbc.JdbcDirectoryMetadataFactory.openDatabase(JdbcDirectoryMetadataFactory.kt:64)
    at de.qabel.box.storage.jdbc.JdbcDirectoryMetadataFactory.open(JdbcDirectoryMetadataFactory.kt:44)
    at de.qabel.box.storage.jdbc.JdbcDirectoryMetadataFactory.open(JdbcDirectoryMetadataFactory.kt:16)
    at de.qabel.box.storage.IndexDMDownloader.loadDirectoryMetadata(IndexDMDownloader.kt:35)
    at de.qabel.box.storage.BoxVolumeImpl.navigate(BoxVolumeImpl.kt:75)
    at de.qabel.qabelbox.box.interactor.BoxVolumeNavigator$root$2.invoke(BoxVolumeNavigator.kt:21)
    at de.qabel.qabelbox.box.interactor.BoxVolumeNavigator$root$2.invoke(BoxVolumeNavigator.kt:11)
    at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
    at de.qabel.qabelbox.box.interactor.BoxVolumeNavigator.getRoot(BoxVolumeNavigator.kt:0)
    at de.qabel.qabelbox.box.interactor.BoxVolumeNavigator.navigateTo(BoxVolumeNavigator.kt:30)
    at de.qabel.qabelbox.box.interactor.BoxFileBrowser.navigateTo(BoxFileBrowser.kt:0)
    at de.qabel.qabelbox.box.interactor.VolumeNavigator$DefaultImpls.navigateTo$default(VolumeNavigator.kt:12)
    at de.qabel.qabelbox.box.interactor.BoxFileBrowser$list$1.invoke(BoxFileBrowser.kt:94)
    at de.qabel.qabelbox.box.interactor.BoxFileBrowser$list$1.invoke(BoxFileBrowser.kt:21)
    at rx.lang.kotlin.ObservablesKt$sam$OnSubscribe$5dafc494.call(observables.kt)
    at rx.lang.kotlin.ObservablesKt$sam$OnSubscribe$5dafc494.call(observables.kt)
    at rx.Observable.unsafeSubscribe(Observable.java:8460)
    at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
    at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:222)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
 Caused by: de.qabel.core.repository.exception.TransactionException: android.database.sqlite.SQLiteException: table meta already exists (code 1): , while compiling: CREATE TABLE meta (
                name VARCHAR(24) PRIMARY KEY,
                value TEXT )
    at de.qabel.core.repository.sqlite.SqliteTransactionManager.transactional(SqliteTransactionManager.java:61)
    at de.qabel.core.repository.sqlite.AbstractClientDatabase.migrate(AbstractClientDatabase.kt:44)
    	... 29 more
 Caused by: java.sql.SQLException: android.database.sqlite.SQLiteException: table meta already exists (code 1): , while compiling: CREATE TABLE meta (
                name VARCHAR(24) PRIMARY KEY,
                value TEXT )
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at org.sqldroid.SQLDroidConnection.chainException(SQLDroidConnection.java:158)
    at org.sqldroid.SQLiteDatabase.execSQL(SQLiteDatabase.java:147)
    at org.sqldroid.SQLDroidPreparedStatement.execute(SQLDroidPreparedStatement.java:190)
    at de.qabel.core.repository.sqlite.migration.AbstractMigration.execute(AbstractMigration.java:21)
    at de.qabel.box.storage.jdbc.migration.DMMigration1467796453Init.up(DMMigration1467796453Init.kt:10)
	at d

**Comment by audax** [comment]
Fixed in the core.
