### ISSUE TITLE
Missing sqlite jdbc library on some devices, Android 7.0 compatibility

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#713]
Reported device names:

- Nexus 5X (bullhead)
- Nexus 9 (flounder)

Reported android version: Android 7.0

Reported 3 times in the last months.

```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/de.qabel.qabel-2/base.apk"],nativeLibraryDirectories=[/data/app/de.qabel.qabel-2/lib/arm64, /system/fake-libs64, /data/app/de.qabel.qabel-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libsqlitejdbc.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:972)
	at java.lang.System.loadLibrary(System.java:1530)
	at org.sqlite.core.NativeDB.<clinit>(NativeDB.java:35)
	at org.sqlite.core.NativeDB.load(NativeDB.java)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:211)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(DriverManager.java:569)
	at java.sql.DriverManager.getConnection(DriverManager.java:237)
	at de.qabel.qabelbox.persistence.RepositoryFactory.getAndroidClientDatabase(RepositoryFactory.kt:66)
	at de.qabel.qabelbox.persistence.RepositoryFactory.getDropUrlRepository(RepositoryFactory.kt:109)
	at de.qabel.qabelbox.persistence.RepositoryFactory.getIdentityRepository(RepositoryFactory.kt:93)
	at de.qabel.qabelbox.dagger.modules.RepositoryModule.provideIdentityRepository(RepositoryModule.java:28)
	at de.qabel.qabelbox.dagger.modules.RepositoryModule_ProvideIdentityRepositoryFactory.get(RepositoryModule_ProvideIdentityRepositoryFactory.java:31)
	at de.qabel.qabelbox.dagger.modules.RepositoryModule_ProvideIdentityRepositoryFactory.get(RepositoryModule_ProvideIdentityRepositoryFactory.java:10)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:46)
	at de.qabel.qabelbox.dagger.modules.BoxModule_ProvideVolumeManagerFactory.get(BoxModule_ProvideVolumeManagerFactory.java:56)
	at de.qabel.qabelbox.dagger.modules.BoxModule_ProvideVolumeManagerFactory.get(BoxModule_ProvideVolumeManagerFactory.java:14)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:46)
	at de.qabel.qabelbox.box.interactor.BoxDocumentIdAdapter_Factory.get(BoxDocumentIdAdapter_Factory.java:41)
	at de.qabel.qabelbox.box.interactor.BoxDocumentIdAdapter_Factory.get(BoxDocumentIdAdapter_Factory.java:10)
	at de.qabel.qabelbox.dagger.modules.BoxModule_ProvideProviderUseCaseFactory.get(BoxModule_ProvideProviderUseCaseFactory.java:30)
	at de.qabel.qabelbox.dagger.modules.BoxModule_ProvideProviderUseCaseFactory.get(BoxModule_ProvideProviderUseCaseFactory.java:10)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:46)
	at de.qabel.qabelbox.box.provider.BoxProvider_MembersInjector.injectMembers(BoxProvider_MembersInjector.java:29)
	at de.qabel.qabelbox.box.provider.BoxProvider_MembersInjector.injectMembers(BoxProvider_MembersInjector.java:8)
	at de.qabel.qabelbox.dagger.components.DaggerBoxComponent.inject(DaggerBoxComponent.java:165)
	at de.qabel.qabelbox.box.provider.BoxProvider.inject(BoxProvider.kt:61)
	at de.qabel.qabelbox.box.provider.BoxProvider.onCreate(BoxProvider.kt:51)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
	at android.provider.DocumentsProvider.attachInfo(DocumentsProvider.java:177)
	at android.app.ActivityThread.installProvider(ActivityThread.java:5811)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5403)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5342)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by thechauffeur** [comment]
See #726.

**Comment by thechauffeur** [comment]
This is time-critical now because we cannot decrease the supported API version in Google Play anymore and therefore cannot exclude Android 7.
