### ISSUE TITLE
Missing String Ressource crash

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#794]
https://rink.hockeyapp.net/manage/apps/280963/app_versions/109/crash_reasons/142697365?type=crashes

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.qabel.qabel/de.qabel.qabelbox.activities.CreateAccountActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.access$900(ActivityThread.java:150)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
	at android.content.res.Resources.getText(Resources.java:312)
	at android.widget.TextView.setText(TextView.java:4425)
	at de.qabel.qabelbox.fragments.CreateIdentityEditTextFragment.onCreateView(CreateIdentityEditTextFragment.java:61)
	at android.app.Fragment.performCreateView(Fragment.java:2220)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1953)
	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:152)
	at android.app.Activity.performCreateCommon(Activity.java:6285)
	at android.app.Activity.performCreate(Activity.java:6293)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
	... 9 more
```

**Comment by audax** [comment]
I checked the code, it is just fine. Since this crash only happened to one user a while ago, I propose to just close this. I can not think of a way to reproduce this error.
