### ISSUE TITLE
Crash in password reset fragment

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#817]
```
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:200)
	at android.os.Handler.<init>(Handler.java:114)
	at android.widget.Toast$TN.<init>(Toast.java:348)
	at android.widget.Toast.<init>(Toast.java:104)
	at android.widget.Toast.makeText(Toast.java:262)
	at android.widget.Toast.makeText(Toast.java:289)
	at de.qabel.qabelbox.startup.fragments.CreateAccountResetPasswordFragment$1.onError(CreateAccountResetPasswordFragment.java:109)
	at de.qabel.qabelbox.communication.callbacks.RequestCallback.onResponse(RequestCallback.java:55)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```
https://rink.hockeyapp.net/manage/apps/280963/app_versions/113/crash_reasons/150041194

**Comment by audax** [comment]
resolved in #814
